// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"aCupOfGin/internal/controllers/userController"
	"aCupOfGin/internal/repos/userRepo"
	"aCupOfGin/internal/services/userService"
	"aCupOfGin/internal/tools/dbManager"
)

// Injectors from wireControllers.go:

func InitUserController(us userService.InterfaceUserService) *userController.ImplementUserController {
	implementUserController := userController.NewUserController(us)
	return implementUserController
}

// Injectors from wireRepos.go:

func InitUserRepo(dm dbManager.InterfaceDBManger) *userRepo.GormUserRepo {
	gormUserRepo := userRepo.NewGormUserRepo(dm)
	return gormUserRepo
}

// Injectors from wireServices.go:

func InitUserService(ur userRepo.InterfaceUserRepo) *userService.ImplementUserService {
	implementUserService := userService.NewUserService(ur)
	return implementUserService
}

// Injectors from wireTools.go:

func InitGormDBManager(Dialector dbManager.DBDialector, DBMaxIdleConns dbManager.DBMaxIdleConns, DBMaxOpenConns dbManager.DBMaxOpenConns, ConnMaxLifeTimeMinutes dbManager.ConnMaxLifeTimeMinutes) *dbManager.GormDBManager {
	dbmSetting := dbManager.NewDBMSetting(Dialector, DBMaxIdleConns, DBMaxOpenConns, ConnMaxLifeTimeMinutes)
	gormDBManager := dbManager.NewGormDBManager(dbmSetting)
	return gormDBManager
}
